# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
import numpy as np
arr=np.arange(8)
arr.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [8]:
arr1=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr2=np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [9]:
arr1=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr2=np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [11]:
arr1=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [12]:
arr3=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14]])
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
arr3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [14]:
arr3.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [17]:
k=np.random.rand(5,5)*10
k

array([[3.34590916, 7.36417075, 8.5883668 , 2.90041342, 0.58812356],
       [7.05571466, 0.40908379, 5.15732833, 2.08310855, 1.4779186 ],
       [1.22850117, 0.66502766, 6.86232993, 9.88336465, 6.88532322],
       [1.2140652 , 3.95618987, 2.44570737, 9.21113457, 4.15364497],
       [6.60379995, 5.47695024, 2.1258536 , 7.73858485, 8.22882505]])

In [18]:
np.power(k,2)

array([[11.19510809, 54.23101091, 73.76004428,  8.41239801,  0.34588932],
       [49.78310941,  0.16734954, 26.59803553,  4.33934121,  2.18424339],
       [ 1.50921514,  0.44226179, 47.09157206, 97.68089674, 47.40767578],
       [ 1.47395432, 15.65143831,  5.98148452, 84.84500008, 17.25276657],
       [43.61017372, 29.99698389,  4.51925353, 59.88569543, 67.71356164]])

## Question:8

### Create 5x6 an array and find the mean?

In [20]:
k=np.random.rand(5,6)*10
k

array([[2.06371243, 6.65286468, 4.82947337, 9.41855513, 2.25238924,
        4.35975601],
       [7.53278822, 3.73587331, 5.57892042, 3.627218  , 2.8722474 ,
        0.95389143],
       [1.66943856, 2.63863254, 8.80884943, 8.52140287, 6.04328007,
        0.9440533 ],
       [4.96086023, 0.33516893, 3.50594547, 6.07312656, 4.30558206,
        0.44307498],
       [8.05934066, 2.53571013, 9.5343314 , 9.36108598, 6.72686369,
        1.47932746]])

In [21]:
k.mean()

4.6607921321427845

## Question:9

### Find the standard deviation of the previous array in Q8?

In [24]:
k.std()

2.8544867199801756

## Question:10

### Find the median of the previous array in Q8?

In [26]:
np.median(k)

4.332669038949364

## Question:11

### Find the transpose of the previous array in Q8?

In [28]:
np.transpose(k)

array([[2.06371243, 7.53278822, 1.66943856, 4.96086023, 8.05934066],
       [6.65286468, 3.73587331, 2.63863254, 0.33516893, 2.53571013],
       [4.82947337, 5.57892042, 8.80884943, 3.50594547, 9.5343314 ],
       [9.41855513, 3.627218  , 8.52140287, 6.07312656, 9.36108598],
       [2.25238924, 2.8722474 , 6.04328007, 4.30558206, 6.72686369],
       [4.35975601, 0.95389143, 0.9440533 , 0.44307498, 1.47932746]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [29]:
v=np.random.rand(4,4)
v

array([[0.11836641, 0.86012966, 0.55857654, 0.6816221 ],
       [0.24172341, 0.45965823, 0.04345524, 0.51456468],
       [0.16543115, 0.64141835, 0.36200668, 0.83370631],
       [0.57206023, 0.83489992, 0.39018762, 0.3864571 ]])

In [30]:
v.trace()

1.3264884161828518

## Question:13

### Find the determinant of the previous array in Q12?

In [31]:
np.linalg.det(v)

0.025690082279595978

## Question:14

### Find the 5th and 95th percentile of an array?

In [32]:
np.percentile(v,5)

0.09963862034719503

In [33]:
np.percentile(v,95)

0.8412073568802898

## Question:15

### How to find if a given array has any null values?

In [34]:
y=[0,1,3,0,4,0,6,7,8,9]
x=np.array(y)
n=x==0
n.any()

True